### ISSUE TITLE
Bypass tamper detection

### ISSUE THREAD

**Issue by venkata16sidhartha** [darvincisec/DetectTamper#4]
Ive made small change in the smali code and recompiled and re-run, and i am able to bypass tamper detection. 

Adding a new line of code:
![image](https://user-images.githubusercontent.com/46317898/175466637-ba745465-885f-4da7-b3e7-1d357bfc0a67.png)

After compiling:
![image](https://user-images.githubusercontent.com/46317898/175466693-7badc2c4-da6c-4984-a7c7-3c5d7b7bdfee.png)

Does this logic work in any tamper detection?

Additionally, is there a frida script or can we make one, to bypass this type of detection? in runtime?

**Comment by darvincisec** [comment]
ofcourse you can bypass it like this. But the spirit of this project is to integrate the native code as part of the larger business logic to detect tampering and react accordingly. The APK given is for demonstrating the functionality with simple java apis and the challenge here is to bypass it at the native level. So, don't waste time bypassing at the java level.
